export const inputCSVcolumnHeaders = [
  "rating",
  "sitter_image",
  "end_date",
  "text",
  "owner_image",
  "dogs",
  "sitter",
  "owner",
  "start_date",
  "sitter_phone_number",
  "sitter_email",
  "owner_phone_number",
  "owner_email",
  "response_time_minutes",
];

// ---------

// length = 1
export const emailOneInput = [
  {
    Name: "Adobe",
    Title: "Adobe",
    Domain: "adobe.com",
    BreachDate: "2013-10-04",
    AddedDate: "2013-12-04T00:00:00Z",
    ModifiedDate: "2022-05-15T23:52:49Z",
    PwnCount: 152445165,
    Description:
      'In October 2013, 153 million Adobe accounts were breached with each containing an internal ID, username, email, <em>encrypted</em> password and a password hint in plain text. The password cryptography was poorly done and many were quickly resolved back to plain text. The unencrypted hints also <a href="http://www.troyhunt.com/2013/11/adobe-credentials-and-serious.html" target="_blank" rel="noopener">disclosed much about the passwords</a> adding further to the risk that hundreds of millions of Adobe customers already faced.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Adobe.png",
    DataClasses: [
      "Email addresses",
      "Password hints",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];

// length = 1
export const emailOneExpectedOutput = [
  {
    Name: "Adobe",
    Title: "Adobe",
    Domain: "adobe.com",
    BreachDate: "2013-10-04",
    AddedDate: "2013-12-04T00:00:00Z",
    ModifiedDate: "2022-05-15T23:52:49Z",
    PwnCount: 152445165,
    Description:
      'In October 2013, 153 million Adobe accounts were breached with each containing an internal ID, username, email, <em>encrypted</em> password and a password hint in plain text. The password cryptography was poorly done and many were quickly resolved back to plain text. The unencrypted hints also <a href="http://www.troyhunt.com/2013/11/adobe-credentials-and-serious.html" target="_blank" rel="noopener">disclosed much about the passwords</a> adding further to the risk that hundreds of millions of Adobe customers already faced.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Adobe.png",
    DataClasses: [
      "Email addresses",
      "Password hints",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];

// ---------

// length = 20
export const emailThreeInput = [
  {
    Name: "B2BUSABusinesses",
    Title: "B2B USA Businesses",
    Domain: "",
    BreachDate: "2017-07-18",
    AddedDate: "2017-07-18T07:38:04Z",
    ModifiedDate: "2017-07-18T07:38:04Z",
    PwnCount: 105059554,
    Description: `In mid-2017, a spam list of over 105 million individuals in corporate America was discovered online. Referred to as &quot;B2B USA Businesses&quot;, the list categorised email addresses by employer, providing information on individuals' job titles plus their work phone numbers and physical addresses. <a href="https://www.troyhunt.com/have-i-been-pwned-and-spam-lists-of-personal-information" target="_blank" rel="noopener">Read more about spam lists in HIBP.</a>`,
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
    DataClasses: [
      "Email addresses",
      "Employers",
      "Job titles",
      "Names",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: true,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Bitly",
    Title: "Bitly",
    Domain: "bitly.com",
    BreachDate: "2014-05-08",
    AddedDate: "2017-10-06T06:31:50Z",
    ModifiedDate: "2017-10-06T08:05:10Z",
    PwnCount: 9313136,
    Description: `In May 2014, the link management company <a href="https://bitly.com/blog/urgent-security-update-regarding-your-bitly-account/" target="_blank" rel="noopener">Bitly announced they'd suffered a data breach</a>. The breach contained over 9.3 million unique email addresses, usernames and hashed passwords, most using SHA1 with a small number using bcrypt.`,
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Bitly.png",
    DataClasses: ["Email addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Canva",
    Title: "Canva",
    Domain: "canva.com",
    BreachDate: "2019-05-24",
    AddedDate: "2019-08-09T14:24:01Z",
    ModifiedDate: "2019-08-09T14:24:01Z",
    PwnCount: 137272116,
    Description:
      'In May 2019, the graphic design tool website <a href="https://support.canva.com/contact/customer-support/may-24-security-incident-faqs/" target="_blank" rel="noopener">Canva suffered a data breach</a> that impacted 137 million subscribers. The exposed data included email addresses, usernames, names, cities of residence and passwords stored as bcrypt hashes for users not using social logins. The data was provided to HIBP by a source who requested it be attributed to "JimScott.Sec@protonmail.com".',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Canva.png",
    DataClasses: [
      "Email addresses",
      "Geographic locations",
      "Names",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "TelegramCombolists",
    Title: "Combolists Posted to Telegram",
    Domain: "",
    BreachDate: "2024-05-28",
    AddedDate: "2024-06-03T19:10:03Z",
    ModifiedDate: "2024-06-11T07:01:09Z",
    PwnCount: 361468099,
    Description:
      'In May 2024, <a href="https://troyhunt.com/telegram-combolists-and-361m-email-addresses" target="_blank" rel="noopener">2B rows of data with 361M unique email addresses were collated from malicious Telegram channels</a>. The data contained 122GB across 1.7k files with email addresses, usernames, passwords and in many cases, the website they were entered into. The data appears to have been sourced from a combination of existing combolists and info stealer malware.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: ["Email addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "db8151dd",
    Title: "Covve",
    Domain: "covve.com",
    BreachDate: "2020-02-20",
    AddedDate: "2020-05-15T08:06:11Z",
    ModifiedDate: "2020-05-19T20:25:18Z",
    PwnCount: 22802117,
    Description:
      'In February 2020, <a href="https://www.troyhunt.com/the-unattributable-db8151dd-data-breach" target="_blank" rel="noopener">a massive trove of personal information referred to as &quot;db8151dd&quot;</a> was provided to HIBP after being found left exposed on a publicly facing Elasticsearch server. Later identified as originating from the Covve contacts app, the exposed data included extensive personal information and interactions between Covve users and their contacts. The data was provided to HIBP by <a href="https://dehashed.com/" target="_blank" rel="noopener">dehashed.com</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Covve.png",
    DataClasses: [
      "Email addresses",
      "Job titles",
      "Names",
      "Phone numbers",
      "Physical addresses",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "PDL",
    Title: "Data Enrichment Exposure From PDL Customer",
    Domain: "",
    BreachDate: "2019-10-16",
    AddedDate: "2019-11-22T20:13:04Z",
    ModifiedDate: "2019-11-22T20:13:04Z",
    PwnCount: 622161052,
    Description: `In October 2019, <a href="https://www.troyhunt.com/data-enrichment-people-data-labs-and-another-622m-email-addresses" target="_blank" rel="noopener">security researchers Vinny Troia and Bob Diachenko identified an unprotected Elasticsearch server holding 1.2 billion records of personal data</a>. The exposed data included an index indicating it was sourced from data enrichment company People Data Labs (PDL) and contained 622 million unique email addresses. The server was not owned by PDL and it's believed a customer failed to properly secure the database. Exposed information included email addresses, phone numbers, social media profiles and job history data.`,
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: [
      "Email addresses",
      "Employers",
      "Geographic locations",
      "Job titles",
      "Names",
      "Phone numbers",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Dropbox",
    Title: "Dropbox",
    Domain: "dropbox.com",
    BreachDate: "2012-07-01",
    AddedDate: "2016-08-31T00:19:19Z",
    ModifiedDate: "2016-08-31T00:19:19Z",
    PwnCount: 68648009,
    Description:
      'In mid-2012, Dropbox suffered a data breach which exposed the stored credentials of tens of millions of their customers. In August 2016, <a href="https://motherboard.vice.com/read/dropbox-forces-password-resets-after-user-credentials-exposed" target="_blank" rel="noopener">they forced password resets for customers they believed may be at risk</a>. A large volume of data totalling over 68 million records <a href="https://motherboard.vice.com/read/hackers-stole-over-60-million-dropbox-accounts" target="_blank" rel="noopener">was subsequently traded online</a> and included email addresses and salted hashes of passwords (half of them SHA1, half of them bcrypt).',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Dropbox.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "ExploreTalent",
    Title: "Explore Talent",
    Domain: "exploretalent.com",
    BreachDate: "2022-02-28",
    AddedDate: "2024-07-25T03:21:40Z",
    ModifiedDate: "2024-07-25T03:21:40Z",
    PwnCount: 5371574,
    Description:
      'In July 2024, <a href="https://x.com/H4ckManac/status/1813528139881988225" target="_blank" rel="noopener">a data breach attributed to Explore Talent was publicly posted to a popular hacking forum</a>. Containing 5.7M rows with 5.4M unique email addresses, the incident has been described by various sources as occurring between early 2022 to 2023 and also contains names, phone numbers and physical addresses.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/ExploreTalent.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Eye4Fraud",
    Title: "Eye4Fraud",
    Domain: "eye4fraud.com",
    BreachDate: "2023-01-25",
    AddedDate: "2023-03-06T04:46:58Z",
    ModifiedDate: "2023-03-06T06:04:28Z",
    PwnCount: 16000591,
    Description: `In February 2023, <a href="https://twitter.com/FalconFeedsio/status/1622838659689988098" target="_blank" rel="noopener">data alleged to have been taken from the fraud protection service Eye4Fraud was listed for sale on a popular hacking forum</a>. Spanning tens of millions of rows with 16M unique email addresses, the data was spread across 147 tables totalling 65GB and included both direct users of the service and what appears to be individuals who'd placed orders on other services that implemented Eye4Fraud to protect their sales. The data included names and bcrypt password hashes for users, and names, phone numbers, physical addresses and partial credit card data (card type and last 4 digits) for orders placed using the service. Eye4Fraud did not respond to multiple attempts to report the incident.`,
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Eye4Fraud.png",
    DataClasses: [
      "Email addresses",
      "IP addresses",
      "Names",
      "Partial credit card data",
      "Passwords",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Gravatar",
    Title: "Gravatar",
    Domain: "gravatar.com",
    BreachDate: "2020-10-03",
    AddedDate: "2021-12-05T22:45:58Z",
    ModifiedDate: "2021-12-08T01:47:02Z",
    PwnCount: 113990759,
    Description: `In October 2020, <a href="https://www.bleepingcomputer.com/news/security/online-avatar-service-gravatar-allows-mass-collection-of-user-info/" target="_blank" rel="noopener">a security researcher published a technique for scraping large volumes of data from Gravatar, the service for providing globally unique avatars </a>. 167 million names, usernames and MD5 hashes of email addresses used to reference users' avatars were subsequently scraped and distributed within the hacking community. 114 million of the MD5 hashes were cracked and distributed alongside the source hash, thus disclosing the original email address and accompanying data. Following the impacted email addresses being searchable in HIBP, <a href="https://en.gravatar.com/support/data-privacy" target="_blank" rel="noopener">Gravatar release an FAQ detailing the incident</a>.`,
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Gravatar.png",
    DataClasses: ["Email addresses", "Names", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "LinkedIn",
    Title: "LinkedIn",
    Domain: "linkedin.com",
    BreachDate: "2012-05-05",
    AddedDate: "2016-05-21T21:35:40Z",
    ModifiedDate: "2016-05-21T21:35:40Z",
    PwnCount: 164611595,
    Description:
      'In May 2016, <a href="https://www.troyhunt.com/observations-and-thoughts-on-the-linkedin-data-breach" target="_blank" rel="noopener">LinkedIn had 164 million email addresses and passwords exposed</a>. Originally hacked in 2012, the data remained out of sight until being offered for sale on a dark market site 4 years later. The passwords in the breach were stored as SHA1 hashes without salt, the vast majority of which were quickly cracked in the days following the release of the data.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/LinkedIn.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "LinkedInScrape",
    Title: "LinkedIn Scraped Data (2021)",
    Domain: "linkedin.com",
    BreachDate: "2021-04-08",
    AddedDate: "2021-10-02T21:39:21Z",
    ModifiedDate: "2023-11-07T06:51:33Z",
    PwnCount: 125698496,
    Description:
      'During the first half of 2021, <a href="https://www.businessinsider.com.au/linkedin-data-scraped-500-million-users-for-sale-online-2021-4" target="_blank" rel="noopener">LinkedIn was targeted by attackers who scraped data from hundreds of millions of public profiles and later sold them online</a>. Whilst the scraping did not constitute a data breach nor did it access any personal data not intended to be publicly accessible, the data was still monetised and later broadly circulated in hacking circles. The scraped data contains approximately 400M records with 125M unique email addresses, as well as names, geographic locations, genders and job titles. LinkedIn specifically addresses the incident in their post on <a href="https://news.linkedin.com/2021/june/an-update-from-linkedin" target="_blank" rel="noopener">An update on report of scraped data</a>.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/LinkedIn.png",
    DataClasses: [
      "Education levels",
      "Email addresses",
      "Genders",
      "Geographic locations",
      "Job titles",
      "Names",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Luxottica",
    Title: "Luxottica",
    Domain: "luxottica.com",
    BreachDate: "2021-03-16",
    AddedDate: "2023-05-19T20:24:45Z",
    ModifiedDate: "2023-05-19T20:24:45Z",
    PwnCount: 77093812,
    Description: `In March 2021, the world's largest eyewear company <a href="https://www.bleepingcomputer.com/news/security/luxottica-confirms-2021-data-breach-after-info-of-70m-leaks-online/" target="_blank" rel="noopener">Luxoticca suffered a data breach via one of their partners that exposed the personal information of more than 70M people</a>. The data was subsequently sold via a popular hacking forum in late 2022 and included email and physical addresses, names, genders, dates of birth and phone numbers. In a statement from Luxottica, they advised they were aware of the incident and are currently &quot;considering other notification obligations&quot;.`,
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Luxottica.png",
    DataClasses: [
      "Dates of birth",
      "Email addresses",
      "Genders",
      "Names",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "MyFitnessPal",
    Title: "MyFitnessPal",
    Domain: "myfitnesspal.com",
    BreachDate: "2018-02-01",
    AddedDate: "2019-02-21T19:28:46Z",
    ModifiedDate: "2019-02-21T20:00:56Z",
    PwnCount: 143606147,
    Description:
      'In February 2018, the diet and exercise service <a href="https://content.myfitnesspal.com/security-information/FAQ.html" target="_blank" rel="noopener">MyFitnessPal suffered a data breach</a>. The incident exposed 144 million unique email addresses alongside usernames, IP addresses and passwords stored as SHA-1 and bcrypt hashes (the former for earlier accounts, the latter for newer accounts). In 2019, <a href="https://www.theregister.co.uk/2019/02/11/620_million_hacked_accounts_dark_web/" target="_blank" rel="noopener">the data appeared listed for sale on a dark web marketplace</a> (along with several other large breaches) and subsequently began circulating more broadly. The data was provided to HIBP by a source who requested it to be attributed to &quot;BenjaminBlue@exploit.im&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/MyFitnessPal.png",
    DataClasses: ["Email addresses", "IP addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "StockX",
    Title: "StockX",
    Domain: "stockx.com",
    BreachDate: "2019-07-26",
    AddedDate: "2019-08-10T15:34:08Z",
    ModifiedDate: "2019-08-11T04:12:11Z",
    PwnCount: 6840339,
    Description:
      'In July 2019, the fashion and sneaker trading platform <a href="https://stockx.com/news/update-on-data-security-issue/" target="_blank" rel="noopener">StockX suffered a data breach</a> which was subsequently sold via a dark webmarketplace. The exposed data included 6.8 million unique email addresses, names, physical addresses, purchases and passwords stored as salted MD5 hashes. The data was provided to HIBP by <a href="https://dehashed.com/" target="_blank" rel="noopener">dehashed.com</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/StockX.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Passwords",
      "Physical addresses",
      "Purchases",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "StreetEasy",
    Title: "StreetEasy",
    Domain: "streeteasy.com",
    BreachDate: "2016-06-28",
    AddedDate: "2019-10-06T18:18:50Z",
    ModifiedDate: "2019-10-06T18:25:03Z",
    PwnCount: 988230,
    Description:
      'In approximately June 2016, the real estate website <a href="https://therealdeal.com/2019/02/19/a-million-streeteasy-accounts-hacked/" target="_blank" rel="noopener">StreetEasy suffered a data breach</a>. In total, 988k unique email addresses were included in the breach alongside names, usernames and SHA-1 hashes of passwords, all of which appeared for sale on a dark web marketplace in February 2019. The data was provided to HIBP by a source who requested it be attributed to &quot;JimScott.Sec@protonmail.com&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/StreetEasy.png",
    DataClasses: ["Email addresses", "Names", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Ticketfly",
    Title: "Ticketfly",
    Domain: "ticketfly.com",
    BreachDate: "2018-05-31",
    AddedDate: "2018-06-03T06:14:14Z",
    ModifiedDate: "2021-07-23T03:15:33Z",
    PwnCount: 26151608,
    Description:
      'In May 2018, the website for the ticket distribution service <a href="https://motherboard.vice.com/en_us/article/mbk3nx/ticketfly-website-database-hacked-data-breach" target="_blank" rel="noopener">Ticketfly was defaced by an attacker and was subsequently taken offline</a>. The attacker allegedly requested a ransom to share details of the vulnerability with Ticketfly but did not receive a reply and subsequently posted the breached data online to a publicly accessible location. The data included over 26 million unique email addresses along with names, physical addresses and phone numbers. Whilst there were no passwords in the publicly leaked data, <a href="https://support.ticketfly.com/customer/en/portal/articles/2941983-ticketfly-cyber-incident-update" target="_blank" rel="noopener">Ticketfly later issued an incident update</a> and stated that &quot;It is possible, however, that hashed values of password credentials could have been accessed&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Ticketfly.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Twitter200M",
    Title: "Twitter (200M)",
    Domain: "twitter.com",
    BreachDate: "2021-01-01",
    AddedDate: "2023-01-05T20:49:16Z",
    ModifiedDate: "2023-01-05T20:49:16Z",
    PwnCount: 211524284,
    Description:
      'In early 2023, <a href="https://www.bleepingcomputer.com/news/security/200-million-twitter-users-email-addresses-allegedly-leaked-online/" target="_blank" rel="noopener">over 200M records scraped from Twitter appeared on a popular hacking forum</a>. The data was obtained sometime in 2021 by abusing an API that enabled email addresses to be resolved to Twitter profiles. The subsequent results were then composed into a corpus of data containing email addresses alongside public Twitter profile information including names, usernames and follower counts.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Twitter.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Social media profiles",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "YouveBeenScraped",
    Title: "You've Been Scraped",
    Domain: "",
    BreachDate: "2018-10-05",
    AddedDate: "2018-12-06T19:11:27Z",
    ModifiedDate: "2018-12-06T19:11:27Z",
    PwnCount: 66147869,
    Description: `In October and November 2018, <a href="https://blog.hackenproof.com/industry-news/new-report-unknown-data-scraper-breach/" target="_blank" rel="noopener">security researcher Bob Diachenko identified several unprotected MongoDB instances believed to be hosted by a data aggregator</a>. Containing a total of over 66M records, the owner of the data couldn't be identified but it is believed to have been scraped from LinkedIn hence the title &quot;You've Been Scraped&quot;. The exposed records included names, both work and personal email addresses, job titles and links to the individuals' LinkedIn profiles.`,
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: [
      "Email addresses",
      "Employers",
      "Geographic locations",
      "Job titles",
      "Names",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Zynga",
    Title: "Zynga",
    Domain: "zynga.com",
    BreachDate: "2019-09-01",
    AddedDate: "2019-12-19T04:54:45Z",
    ModifiedDate: "2020-01-11T00:41:51Z",
    PwnCount: 172869660,
    Description:
      'In September 2019, game developer <a href="https://www.cnet.com/news/words-with-friends-hack-reportedly-exposes-data-of-more-than-200m-players/" target="_blank" rel="noopener">Zynga (the creator of Words with Friends) suffered a data breach</a>. The incident exposed 173M unique email addresses alongside usernames and passwords stored as salted SHA-1 hashes. The data was provided to HIBP by <a href="https://dehashed.com/" target="_blank" rel="noopener">dehashed.com</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Zynga.png",
    DataClasses: ["Email addresses", "Passwords", "Phone numbers", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];

// length = 6
export const emailTwoExpectedOutput = [
  {
    Name: "Adobe",
    Title: "Adobe",
    Domain: "adobe.com",
    BreachDate: "2013-10-04",
    AddedDate: "2013-12-04T00:00:00Z",
    ModifiedDate: "2022-05-15T23:52:49Z",
    PwnCount: 152445165,
    Description:
      'In October 2013, 153 million Adobe accounts were breached with each containing an internal ID, username, email, <em>encrypted</em> password and a password hint in plain text. The password cryptography was poorly done and many were quickly resolved back to plain text. The unencrypted hints also <a href="http://www.troyhunt.com/2013/11/adobe-credentials-and-serious.html" target="_blank" rel="noopener">disclosed much about the passwords</a> adding further to the risk that hundreds of millions of Adobe customers already faced.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Adobe.png",
    DataClasses: [
      "Email addresses",
      "Password hints",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "CafePress",
    Title: "CafePress",
    Domain: "cafepress.com",
    BreachDate: "2019-02-20",
    AddedDate: "2019-08-05T01:18:43Z",
    ModifiedDate: "2019-08-05T20:02:32Z",
    PwnCount: 23205290,
    Description:
      'In February 2019, the custom merchandise retailer <a href="https://www.cafepress.com/" target="_blank" rel="noopener">CafePress</a> suffered a data breach. The exposed data included 23 million unique email addresses with some records also containing names, physical addresses, phone numbers and passwords stored as SHA-1 hashes. The data was provided to HIBP by a source who requested it be attributed to "JimScott.Sec@protonmail.com".',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/CafePress.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Passwords",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Collection1",
    Title: "Collection #1",
    Domain: "",
    BreachDate: "2019-01-07",
    AddedDate: "2019-01-16T21:46:07Z",
    ModifiedDate: "2019-01-16T21:50:21Z",
    PwnCount: 772904991,
    Description:
      'In January 2019, a large collection of credential stuffing lists (combinations of email addresses and passwords used to hijack accounts on other services) was discovered being distributed on a popular hacking forum. The data contained almost 2.7 <em>billion</em> records including 773 million unique email addresses alongside passwords those addresses had used on other breached services. Full details on the incident and how to search the breached passwords are provided in the blog post <a href="https://www.troyhunt.com/the-773-million-record-collection-1-data-reach" target="_blank" rel="noopener">The 773 Million Record "Collection #1" Data Breach</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: false,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "DataCamp",
    Title: "DataCamp",
    Domain: "datacamp.com",
    BreachDate: "2017-01-30",
    AddedDate: "2019-04-09T04:29:55Z",
    ModifiedDate: "2019-04-09T21:12:53Z",
    PwnCount: 760561,
    Description:
      'In December 2018, the data science website <a href="https://support.datacamp.com/hc/en-us/articles/360017716074-DataCamp-Security-Update-Frequently-Asked-Questions" target="_blank" rel="noopener">DataCamp suffered a data breach</a> of records dating back to January 2017. The incident exposed 760k unique email and IP addresses along with names and passwords stored as bcrypt hashes. In 2019, <a href="https://www.theregister.co.uk/2019/02/11/620_million_hacked_accounts_dark_web/" target="_blank" rel="noopener">the data appeared listed for sale on a dark web marketplace</a> (along with several other large breaches) and subsequently began circulating more broadly. The data was provided to HIBP by a source who requested it to be attributed to &quot;BenjaminBlue@exploit.im&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/DataCamp.png",
    DataClasses: [
      "Email addresses",
      "Geographic locations",
      "IP addresses",
      "Names",
      "Passwords",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "LinkedIn",
    Title: "LinkedIn",
    Domain: "linkedin.com",
    BreachDate: "2012-05-05",
    AddedDate: "2016-05-21T21:35:40Z",
    ModifiedDate: "2016-05-21T21:35:40Z",
    PwnCount: 164611595,
    Description:
      'In May 2016, <a href="https://www.troyhunt.com/observations-and-thoughts-on-the-linkedin-data-breach" target="_blank" rel="noopener">LinkedIn had 164 million email addresses and passwords exposed</a>. Originally hacked in 2012, the data remained out of sight until being offered for sale on a dark market site 4 years later. The passwords in the breach were stored as SHA1 hashes without salt, the vast majority of which were quickly cracked in the days following the release of the data.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/LinkedIn.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "OnlinerSpambot",
    Title: "Onliner Spambot",
    Domain: "",
    BreachDate: "2017-08-28",
    AddedDate: "2017-08-29T19:25:56Z",
    ModifiedDate: "2017-08-29T19:25:56Z",
    PwnCount: 711477622,
    Description:
      'In August 2017, a spambot by the name of <a href="https://benkowlab.blogspot.com.au/2017/08/from-onliner-spambot-to-millions-of.html" target="_blank" rel="noopener">Onliner Spambot was identified by security researcher Benkow moʞuƎq</a>. The malicious software contained a server-based component located on an IP address in the Netherlands which exposed a large number of files containing personal information. In total, there were 711 million unique email addresses, many of which were also accompanied by corresponding passwords. A full write-up on what data was found is in the blog post titled <a href="https://www.troyhunt.com/inside-the-massive-711-million-record-onliner-spambot-dump" target="_blank" rel="noopener">Inside the Massive 711 Million Record Onliner Spambot Dump</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: true,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];

// -----------

// length = 12
export const emailTwoInput = [
  {
    Name: "Adobe",
    Title: "Adobe",
    Domain: "adobe.com",
    BreachDate: "2013-10-04",
    AddedDate: "2013-12-04T00:00:00Z",
    ModifiedDate: "2022-05-15T23:52:49Z",
    PwnCount: 152445165,
    Description:
      'In October 2013, 153 million Adobe accounts were breached with each containing an internal ID, username, email, <em>encrypted</em> password and a password hint in plain text. The password cryptography was poorly done and many were quickly resolved back to plain text. The unencrypted hints also <a href="http://www.troyhunt.com/2013/11/adobe-credentials-and-serious.html" target="_blank" rel="noopener">disclosed much about the passwords</a> adding further to the risk that hundreds of millions of Adobe customers already faced.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Adobe.png",
    DataClasses: [
      "Email addresses",
      "Password hints",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "CafePress",
    Title: "CafePress",
    Domain: "cafepress.com",
    BreachDate: "2019-02-20",
    AddedDate: "2019-08-05T01:18:43Z",
    ModifiedDate: "2019-08-05T20:02:32Z",
    PwnCount: 23205290,
    Description:
      'In February 2019, the custom merchandise retailer <a href="https://www.cafepress.com/" target="_blank" rel="noopener">CafePress</a> suffered a data breach. The exposed data included 23 million unique email addresses with some records also containing names, physical addresses, phone numbers and passwords stored as SHA-1 hashes. The data was provided to HIBP by a source who requested it be attributed to "JimScott.Sec@protonmail.com".',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/CafePress.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Passwords",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Collection1",
    Title: "Collection #1",
    Domain: "",
    BreachDate: "2019-01-07",
    AddedDate: "2019-01-16T21:46:07Z",
    ModifiedDate: "2019-01-16T21:50:21Z",
    PwnCount: 772904991,
    Description:
      'In January 2019, a large collection of credential stuffing lists (combinations of email addresses and passwords used to hijack accounts on other services) was discovered being distributed on a popular hacking forum. The data contained almost 2.7 <em>billion</em> records including 773 million unique email addresses alongside passwords those addresses had used on other breached services. Full details on the incident and how to search the breached passwords are provided in the blog post <a href="https://www.troyhunt.com/the-773-million-record-collection-1-data-reach" target="_blank" rel="noopener">The 773 Million Record "Collection #1" Data Breach</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: false,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "PDL",
    Title: "Data Enrichment Exposure From PDL Customer",
    Domain: "",
    BreachDate: "2019-10-16",
    AddedDate: "2019-11-22T20:13:04Z",
    ModifiedDate: "2019-11-22T20:13:04Z",
    PwnCount: 622161052,
    Description: `In October 2019, <a href="https://www.troyhunt.com/data-enrichment-people-data-labs-and-another-622m-email-addresses" target="_blank" rel="noopener">security researchers Vinny Troia and Bob Diachenko identified an unprotected Elasticsearch server holding 1.2 billion records of personal data</a>. The exposed data included an index indicating it was sourced from data enrichment company People Data Labs (PDL) and contained 622 million unique email addresses. The server was not owned by PDL and it's believed a customer failed to properly secure the database. Exposed information included email addresses, phone numbers, social media profiles and job history data.`,
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: [
      "Email addresses",
      "Employers",
      "Geographic locations",
      "Job titles",
      "Names",
      "Phone numbers",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "DataCamp",
    Title: "DataCamp",
    Domain: "datacamp.com",
    BreachDate: "2017-01-30",
    AddedDate: "2019-04-09T04:29:55Z",
    ModifiedDate: "2019-04-09T21:12:53Z",
    PwnCount: 760561,
    Description:
      'In December 2018, the data science website <a href="https://support.datacamp.com/hc/en-us/articles/360017716074-DataCamp-Security-Update-Frequently-Asked-Questions" target="_blank" rel="noopener">DataCamp suffered a data breach</a> of records dating back to January 2017. The incident exposed 760k unique email and IP addresses along with names and passwords stored as bcrypt hashes. In 2019, <a href="https://www.theregister.co.uk/2019/02/11/620_million_hacked_accounts_dark_web/" target="_blank" rel="noopener">the data appeared listed for sale on a dark web marketplace</a> (along with several other large breaches) and subsequently began circulating more broadly. The data was provided to HIBP by a source who requested it to be attributed to &quot;BenjaminBlue@exploit.im&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/DataCamp.png",
    DataClasses: [
      "Email addresses",
      "Geographic locations",
      "IP addresses",
      "Names",
      "Passwords",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Exactis",
    Title: "Exactis",
    Domain: "exactis.com",
    BreachDate: "2018-06-01",
    AddedDate: "2018-07-25T20:00:44Z",
    ModifiedDate: "2018-07-25T20:00:44Z",
    PwnCount: 131577763,
    Description: `In June 2018, <a href="https://www.wired.com/story/exactis-database-leak-340-million-records/" target="_blank" rel="noopener">the marketing firm Exactis inadvertently publicly leaked 340 million records of personal data</a>. Security researcher <a href="https://www.nightlionsecurity.com/" target="_blank" rel="noopener">Vinny Troia of Night Lion Security</a> discovered the leak contained multiple terabytes of personal information spread across hundreds of separate fields including addresses, phone numbers, family structures and extensive profiling data. The data was collected as part of Exactis' service as a &quot;compiler and aggregator of premium business &amp; consumer data&quot; which they then sell for profiling and marketing purposes. A small subset of the exposed fields were provided to Have I Been Pwned and contained 132 million unique email addresses.`,
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Exactis.png",
    DataClasses: [
      "Credit status information",
      "Dates of birth",
      "Education levels",
      "Email addresses",
      "Ethnicities",
      "Family structure",
      "Financial investments",
      "Genders",
      "Home ownership statuses",
      "Income levels",
      "IP addresses",
      "Marital statuses",
      "Names",
      "Net worths",
      "Occupations",
      "Personal interests",
      "Phone numbers",
      "Physical addresses",
      "Religions",
      "Spoken languages",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "LinkedIn",
    Title: "LinkedIn",
    Domain: "linkedin.com",
    BreachDate: "2012-05-05",
    AddedDate: "2016-05-21T21:35:40Z",
    ModifiedDate: "2016-05-21T21:35:40Z",
    PwnCount: 164611595,
    Description:
      'In May 2016, <a href="https://www.troyhunt.com/observations-and-thoughts-on-the-linkedin-data-breach" target="_blank" rel="noopener">LinkedIn had 164 million email addresses and passwords exposed</a>. Originally hacked in 2012, the data remained out of sight until being offered for sale on a dark market site 4 years later. The passwords in the breach were stored as SHA1 hashes without salt, the vast majority of which were quickly cracked in the days following the release of the data.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/LinkedIn.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "LinkedInScrape",
    Title: "LinkedIn Scraped Data (2021)",
    Domain: "linkedin.com",
    BreachDate: "2021-04-08",
    AddedDate: "2021-10-02T21:39:21Z",
    ModifiedDate: "2023-11-07T06:51:33Z",
    PwnCount: 125698496,
    Description:
      'During the first half of 2021, <a href="https://www.businessinsider.com.au/linkedin-data-scraped-500-million-users-for-sale-online-2021-4" target="_blank" rel="noopener">LinkedIn was targeted by attackers who scraped data from hundreds of millions of public profiles and later sold them online</a>. Whilst the scraping did not constitute a data breach nor did it access any personal data not intended to be publicly accessible, the data was still monetised and later broadly circulated in hacking circles. The scraped data contains approximately 400M records with 125M unique email addresses, as well as names, geographic locations, genders and job titles. LinkedIn specifically addresses the incident in their post on <a href="https://news.linkedin.com/2021/june/an-update-from-linkedin" target="_blank" rel="noopener">An update on report of scraped data</a>.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/LinkedIn.png",
    DataClasses: [
      "Education levels",
      "Email addresses",
      "Genders",
      "Geographic locations",
      "Job titles",
      "Names",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "OnlinerSpambot",
    Title: "Onliner Spambot",
    Domain: "",
    BreachDate: "2017-08-28",
    AddedDate: "2017-08-29T19:25:56Z",
    ModifiedDate: "2017-08-29T19:25:56Z",
    PwnCount: 711477622,
    Description:
      'In August 2017, a spambot by the name of <a href="https://benkowlab.blogspot.com.au/2017/08/from-onliner-spambot-to-millions-of.html" target="_blank" rel="noopener">Onliner Spambot was identified by security researcher Benkow moʞuƎq</a>. The malicious software contained a server-based component located on an IP address in the Netherlands which exposed a large number of files containing personal information. In total, there were 711 million unique email addresses, many of which were also accompanied by corresponding passwords. A full write-up on what data was found is in the blog post titled <a href="https://www.troyhunt.com/inside-the-massive-711-million-record-onliner-spambot-dump" target="_blank" rel="noopener">Inside the Massive 711 Million Record Onliner Spambot Dump</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: true,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "QuestionPro",
    Title: "QuestionPro",
    Domain: "questionpro.com",
    BreachDate: "2022-05-21",
    AddedDate: "2022-08-05T00:05:34Z",
    ModifiedDate: "2022-08-05T23:24:27Z",
    PwnCount: 22229637,
    Description:
      'In May 2022, <a href="https://www.bleepingcomputer.com/news/security/hackers-try-to-extort-survey-firm-questionpro-after-alleged-data-theft/" target="_blank" rel="noopener">the survey website QuestionPro was the target of an extortion attempt relating to an alleged data breach</a>. Over 100GB of data containing 22M unique email addresses (some of which appear to be generated by the platform), are alleged to have been extracted from the service along with IP addresses, browser user agents and results relating to surveys. QuestionPro would not confirm whether a breach had occurred (although they did confirm they were the target of an extortion attempt), so the data was initially flagged as &quot;unverified&quot;. <a href="https://twitter.com/troyhunt/status/1555696116351377410" target="_blank" rel="noopener">Subsequent verification by impacted HIBP subscribers</a> later led to the removal of the unverified flag.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/QuestionPro.png",
    DataClasses: [
      "Browser user agent details",
      "Email addresses",
      "IP addresses",
      "Survey results",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "VerificationsIO",
    Title: "Verifications.io",
    Domain: "verifications.io",
    BreachDate: "2019-02-25",
    AddedDate: "2019-03-09T19:29:54Z",
    ModifiedDate: "2019-03-09T20:49:51Z",
    PwnCount: 763117241,
    Description:
      'In February 2019, the email address validation service <a href="https://securitydiscovery.com/800-million-emails-leaked-online-by-email-verification-service" target="_blank" rel="noopener">verifications.io suffered a data breach</a>. Discovered by <a href="https://twitter.com/mayhemdayone" target="_blank" rel="noopener">Bob Diachenko</a> and <a href="https://twitter.com/vinnytroia" target="_blank" rel="noopener">Vinny Troia</a>, the breach was due to the data being stored in a MongoDB instance left publicly facing without a password and resulted in 763 million unique email addresses being exposed. Many records within the data also included additional personal attributes such as names, phone numbers, IP addresses, dates of birth and genders. No passwords were included in the data. The Verifications.io website went offline during the disclosure process, although <a href="https://web.archive.org/web/20190227230352/https://verifications.io/" target="_blank" rel="noopener">an archived copy remains viewable</a>.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/VerificationsIO.png",
    DataClasses: [
      "Dates of birth",
      "Email addresses",
      "Employers",
      "Genders",
      "Geographic locations",
      "IP addresses",
      "Job titles",
      "Names",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "YouveBeenScraped",
    Title: "You've Been Scraped",
    Domain: "",
    BreachDate: "2018-10-05",
    AddedDate: "2018-12-06T19:11:27Z",
    ModifiedDate: "2018-12-06T19:11:27Z",
    PwnCount: 66147869,
    Description: `In October and November 2018, <a href="https://blog.hackenproof.com/industry-news/new-report-unknown-data-scraper-breach/" target="_blank" rel="noopener">security researcher Bob Diachenko identified several unprotected MongoDB instances believed to be hosted by a data aggregator</a>. Containing a total of over 66M records, the owner of the data couldn't be identified but it is believed to have been scraped from LinkedIn hence the title &quot;You've Been Scraped&quot;. The exposed records included names, both work and personal email addresses, job titles and links to the individuals' LinkedIn profiles.`,
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: [
      "Email addresses",
      "Employers",
      "Geographic locations",
      "Job titles",
      "Names",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];

// length = 12
export const emailThreeExpectedOutput = [
  {
    Name: "Bitly",
    Title: "Bitly",
    Domain: "bitly.com",
    BreachDate: "2014-05-08",
    AddedDate: "2017-10-06T06:31:50Z",
    ModifiedDate: "2017-10-06T08:05:10Z",
    PwnCount: 9313136,
    Description:
      'In May 2014, the link management company <a href="https://bitly.com/blog/urgent-security-update-regarding-your-bitly-account/" target="_blank" rel="noopener">Bitly announced they\'d suffered a data breach</a>. The breach contained over 9.3 million unique email addresses, usernames and hashed passwords, most using SHA1 with a small number using bcrypt.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Bitly.png",
    DataClasses: ["Email addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Canva",
    Title: "Canva",
    Domain: "canva.com",
    BreachDate: "2019-05-24",
    AddedDate: "2019-08-09T14:24:01Z",
    ModifiedDate: "2019-08-09T14:24:01Z",
    PwnCount: 137272116,
    Description:
      'In May 2019, the graphic design tool website <a href="https://support.canva.com/contact/customer-support/may-24-security-incident-faqs/" target="_blank" rel="noopener">Canva suffered a data breach</a> that impacted 137 million subscribers. The exposed data included email addresses, usernames, names, cities of residence and passwords stored as bcrypt hashes for users not using social logins. The data was provided to HIBP by a source who requested it be attributed to "JimScott.Sec@protonmail.com".',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Canva.png",
    DataClasses: [
      "Email addresses",
      "Geographic locations",
      "Names",
      "Passwords",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "TelegramCombolists",
    Title: "Combolists Posted to Telegram",
    Domain: "",
    BreachDate: "2024-05-28",
    AddedDate: "2024-06-03T19:10:03Z",
    ModifiedDate: "2024-06-11T07:01:09Z",
    PwnCount: 361468099,
    Description:
      'In May 2024, <a href="https://troyhunt.com/telegram-combolists-and-361m-email-addresses" target="_blank" rel="noopener">2B rows of data with 361M unique email addresses were collated from malicious Telegram channels</a>. The data contained 122GB across 1.7k files with email addresses, usernames, passwords and in many cases, the website they were entered into. The data appears to have been sourced from a combination of existing combolists and info stealer malware.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: ["Email addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Dropbox",
    Title: "Dropbox",
    Domain: "dropbox.com",
    BreachDate: "2012-07-01",
    AddedDate: "2016-08-31T00:19:19Z",
    ModifiedDate: "2016-08-31T00:19:19Z",
    PwnCount: 68648009,
    Description:
      'In mid-2012, Dropbox suffered a data breach which exposed the stored credentials of tens of millions of their customers. In August 2016, <a href="https://motherboard.vice.com/read/dropbox-forces-password-resets-after-user-credentials-exposed" target="_blank" rel="noopener">they forced password resets for customers they believed may be at risk</a>. A large volume of data totalling over 68 million records <a href="https://motherboard.vice.com/read/hackers-stole-over-60-million-dropbox-accounts" target="_blank" rel="noopener">was subsequently traded online</a> and included email addresses and salted hashes of passwords (half of them SHA1, half of them bcrypt).',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Dropbox.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Eye4Fraud",
    Title: "Eye4Fraud",
    Domain: "eye4fraud.com",
    BreachDate: "2023-01-25",
    AddedDate: "2023-03-06T04:46:58Z",
    ModifiedDate: "2023-03-06T06:04:28Z",
    PwnCount: 16000591,
    Description:
      'In February 2023, <a href="https://twitter.com/FalconFeedsio/status/1622838659689988098" target="_blank" rel="noopener">data alleged to have been taken from the fraud protection service Eye4Fraud was listed for sale on a popular hacking forum</a>. Spanning tens of millions of rows with 16M unique email addresses, the data was spread across 147 tables totalling 65GB and included both direct users of the service and what appears to be individuals who\'d placed orders on other services that implemented Eye4Fraud to protect their sales. The data included names and bcrypt password hashes for users, and names, phone numbers, physical addresses and partial credit card data (card type and last 4 digits) for orders placed using the service. Eye4Fraud did not respond to multiple attempts to report the incident.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Eye4Fraud.png",
    DataClasses: [
      "Email addresses",
      "IP addresses",
      "Names",
      "Partial credit card data",
      "Passwords",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Gravatar",
    Title: "Gravatar",
    Domain: "gravatar.com",
    BreachDate: "2020-10-03",
    AddedDate: "2021-12-05T22:45:58Z",
    ModifiedDate: "2021-12-08T01:47:02Z",
    PwnCount: 113990759,
    Description:
      'In October 2020, <a href="https://www.bleepingcomputer.com/news/security/online-avatar-service-gravatar-allows-mass-collection-of-user-info/" target="_blank" rel="noopener">a security researcher published a technique for scraping large volumes of data from Gravatar, the service for providing globally unique avatars </a>. 167 million names, usernames and MD5 hashes of email addresses used to reference users\' avatars were subsequently scraped and distributed within the hacking community. 114 million of the MD5 hashes were cracked and distributed alongside the source hash, thus disclosing the original email address and accompanying data. Following the impacted email addresses being searchable in HIBP, <a href="https://en.gravatar.com/support/data-privacy" target="_blank" rel="noopener">Gravatar release an FAQ detailing the incident</a>.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Gravatar.png",
    DataClasses: ["Email addresses", "Names", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "LinkedIn",
    Title: "LinkedIn",
    Domain: "linkedin.com",
    BreachDate: "2012-05-05",
    AddedDate: "2016-05-21T21:35:40Z",
    ModifiedDate: "2016-05-21T21:35:40Z",
    PwnCount: 164611595,
    Description:
      'In May 2016, <a href="https://www.troyhunt.com/observations-and-thoughts-on-the-linkedin-data-breach" target="_blank" rel="noopener">LinkedIn had 164 million email addresses and passwords exposed</a>. Originally hacked in 2012, the data remained out of sight until being offered for sale on a dark market site 4 years later. The passwords in the breach were stored as SHA1 hashes without salt, the vast majority of which were quickly cracked in the days following the release of the data.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/LinkedIn.png",
    DataClasses: ["Email addresses", "Passwords"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "MyFitnessPal",
    Title: "MyFitnessPal",
    Domain: "myfitnesspal.com",
    BreachDate: "2018-02-01",
    AddedDate: "2019-02-21T19:28:46Z",
    ModifiedDate: "2019-02-21T20:00:56Z",
    PwnCount: 143606147,
    Description:
      'In February 2018, the diet and exercise service <a href="https://content.myfitnesspal.com/security-information/FAQ.html" target="_blank" rel="noopener">MyFitnessPal suffered a data breach</a>. The incident exposed 144 million unique email addresses alongside usernames, IP addresses and passwords stored as SHA-1 and bcrypt hashes (the former for earlier accounts, the latter for newer accounts). In 2019, <a href="https://www.theregister.co.uk/2019/02/11/620_million_hacked_accounts_dark_web/" target="_blank" rel="noopener">the data appeared listed for sale on a dark web marketplace</a> (along with several other large breaches) and subsequently began circulating more broadly. The data was provided to HIBP by a source who requested it to be attributed to &quot;BenjaminBlue@exploit.im&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/MyFitnessPal.png",
    DataClasses: ["Email addresses", "IP addresses", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "StockX",
    Title: "StockX",
    Domain: "stockx.com",
    BreachDate: "2019-07-26",
    AddedDate: "2019-08-10T15:34:08Z",
    ModifiedDate: "2019-08-11T04:12:11Z",
    PwnCount: 6840339,
    Description:
      'In July 2019, the fashion and sneaker trading platform <a href="https://stockx.com/news/update-on-data-security-issue/" target="_blank" rel="noopener">StockX suffered a data breach</a> which was subsequently sold via a dark webmarketplace. The exposed data included 6.8 million unique email addresses, names, physical addresses, purchases and passwords stored as salted MD5 hashes. The data was provided to HIBP by <a href="https://dehashed.com/" target="_blank" rel="noopener">dehashed.com</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/StockX.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Passwords",
      "Physical addresses",
      "Purchases",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "StreetEasy",
    Title: "StreetEasy",
    Domain: "streeteasy.com",
    BreachDate: "2016-06-28",
    AddedDate: "2019-10-06T18:18:50Z",
    ModifiedDate: "2019-10-06T18:25:03Z",
    PwnCount: 988230,
    Description:
      'In approximately June 2016, the real estate website <a href="https://therealdeal.com/2019/02/19/a-million-streeteasy-accounts-hacked/" target="_blank" rel="noopener">StreetEasy suffered a data breach</a>. In total, 988k unique email addresses were included in the breach alongside names, usernames and SHA-1 hashes of passwords, all of which appeared for sale on a dark web marketplace in February 2019. The data was provided to HIBP by a source who requested it be attributed to &quot;JimScott.Sec@protonmail.com&quot;.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/StreetEasy.png",
    DataClasses: ["Email addresses", "Names", "Passwords", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Twitter200M",
    Title: "Twitter (200M)",
    Domain: "twitter.com",
    BreachDate: "2021-01-01",
    AddedDate: "2023-01-05T20:49:16Z",
    ModifiedDate: "2023-01-05T20:49:16Z",
    PwnCount: 211524284,
    Description:
      'In early 2023, <a href="https://www.bleepingcomputer.com/news/security/200-million-twitter-users-email-addresses-allegedly-leaked-online/" target="_blank" rel="noopener">over 200M records scraped from Twitter appeared on a popular hacking forum</a>. The data was obtained sometime in 2021 by abusing an API that enabled email addresses to be resolved to Twitter profiles. The subsequent results were then composed into a corpus of data containing email addresses alongside public Twitter profile information including names, usernames and follower counts.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/Twitter.png",
    DataClasses: [
      "Email addresses",
      "Names",
      "Social media profiles",
      "Usernames",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "Zynga",
    Title: "Zynga",
    Domain: "zynga.com",
    BreachDate: "2019-09-01",
    AddedDate: "2019-12-19T04:54:45Z",
    ModifiedDate: "2020-01-11T00:41:51Z",
    PwnCount: 172869660,
    Description:
      'In September 2019, game developer <a href="https://www.cnet.com/news/words-with-friends-hack-reportedly-exposes-data-of-more-than-200m-players/" target="_blank" rel="noopener">Zynga (the creator of Words with Friends) suffered a data breach</a>. The incident exposed 173M unique email addresses alongside usernames and passwords stored as salted SHA-1 hashes. The data was provided to HIBP by <a href="https://dehashed.com/" target="_blank" rel="noopener">dehashed.com</a>.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Zynga.png",
    DataClasses: ["Email addresses", "Passwords", "Phone numbers", "Usernames"],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];

// -----------

// length = 3 @ July-2024 (all known breaches, unfiltered)
// email = abetaylor@hotmail.com
export const emailFourExpectedOutput = [
  {
    Name: "PDL",
    Title: "Data Enrichment Exposure From PDL Customer",
    Domain: "",
    BreachDate: "2019-10-16",
    AddedDate: "2019-11-22T20:13:04Z",
    ModifiedDate: "2019-11-22T20:13:04Z",
    PwnCount: 622161052,
    Description: `In October 2019, <a href="https://www.troyhunt.com/data-enrichment-people-data-labs-and-another-622m-email-addresses" target="_blank" rel="noopener">security researchers Vinny Troia and Bob Diachenko identified an unprotected Elasticsearch server holding 1.2 billion records of personal data</a>. The exposed data included an index indicating it was sourced from data enrichment company People Data Labs (PDL) and contained 622 million unique email addresses. The server was not owned by PDL and it's believed a customer failed to properly secure the database. Exposed information included email addresses, phone numbers, social media profiles and job history data.`,
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/List.png",
    DataClasses: [
      "Email addresses",
      "Employers",
      "Geographic locations",
      "Job titles",
      "Names",
      "Phone numbers",
      "Social media profiles",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "RiverCityMedia",
    Title: "River City Media Spam List",
    Domain: "rivercitymediaonline.com",
    BreachDate: "2017-01-01",
    AddedDate: "2017-03-08T23:49:53Z",
    ModifiedDate: "2017-03-08T23:49:53Z",
    PwnCount: 393430309,
    Description:
      'In January 2017, <a href="https://web.archive.org/web/20170426084052/https://mackeeper.com/blog/post/339-spammergate-the-fall-of-an-empire" target="_blank" rel="noopener">a massive trove of data from River City Media was found exposed online</a>. The data was found to contain almost 1.4 billion records including email and IP addresses, names and physical addresses, all of which was used as part of an enormous spam operation. Once de-duplicated, there were 393 million unique email addresses within the exposed data.',
    LogoPath: "https://haveibeenpwned.com/Content/Images/PwnedLogos/Email.png",
    DataClasses: [
      "Email addresses",
      "IP addresses",
      "Names",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: true,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
  {
    Name: "VerificationsIO",
    Title: "Verifications.io",
    Domain: "verifications.io",
    BreachDate: "2019-02-25",
    AddedDate: "2019-03-09T19:29:54Z",
    ModifiedDate: "2019-03-09T20:49:51Z",
    PwnCount: 763117241,
    Description:
      'In February 2019, the email address validation service <a href="https://securitydiscovery.com/800-million-emails-leaked-online-by-email-verification-service" target="_blank" rel="noopener">verifications.io suffered a data breach</a>. Discovered by <a href="https://twitter.com/mayhemdayone" target="_blank" rel="noopener">Bob Diachenko</a> and <a href="https://twitter.com/vinnytroia" target="_blank" rel="noopener">Vinny Troia</a>, the breach was due to the data being stored in a MongoDB instance left publicly facing without a password and resulted in 763 million unique email addresses being exposed. Many records within the data also included additional personal attributes such as names, phone numbers, IP addresses, dates of birth and genders. No passwords were included in the data. The Verifications.io website went offline during the disclosure process, although <a href="https://web.archive.org/web/20190227230352/https://verifications.io/" target="_blank" rel="noopener">an archived copy remains viewable</a>.',
    LogoPath:
      "https://haveibeenpwned.com/Content/Images/PwnedLogos/VerificationsIO.png",
    DataClasses: [
      "Dates of birth",
      "Email addresses",
      "Employers",
      "Genders",
      "Geographic locations",
      "IP addresses",
      "Job titles",
      "Names",
      "Phone numbers",
      "Physical addresses",
    ],
    IsVerified: true,
    IsFabricated: false,
    IsSensitive: false,
    IsRetired: false,
    IsSpamList: false,
    IsMalware: false,
    IsSubscriptionFree: false,
  },
];
